# shellcheck shell=bash
#
# lib/project.sh — per-project derivations: slug, free port, URL opener, settings
#
# Sourced by start.sh (not run standalone); see the source-order contract
# there. Pure function definitions, no top-level side effects, so the file
# is safe to source for unit tests.

# derive_slug PATH — lowercase basename, non [a-z0-9_-] -> '-', collapse and
# trim dashes. Falls back to 'project' if nothing survives.
derive_slug() {
  local raw slug
  raw="$(basename -- "$1")"
  slug="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/[^a-z0-9_-]/-/g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')"
  [ -n "$slug" ] || slug="project"
  printf '%s' "$slug"
}

# port_in_use PORT — return 0 if something is already listening on PORT.
port_in_use() {
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${p}\$"
  elif command -v nc >/dev/null 2>&1; then
    nc -z 127.0.0.1 "$p" >/dev/null 2>&1
  else
    # Fall back to bash /dev/tcp probe.
    (exec 3<>"/dev/tcp/127.0.0.1/${p}") >/dev/null 2>&1 && { exec 3>&- 3<&- 2>/dev/null; return 0; } || return 1
  fi
}

# find_free_port START [LIMIT] — echo the first free port >= START, scanning up
# to LIMIT (exclusive; default START+100). Echoes START itself if it is free.
find_free_port() {
  local p="$1" limit="${2:-$(( $1 + 100 ))}"
  while [ "$p" -lt "$limit" ] && port_in_use "$p"; do
    p=$((p + 1))
  done
  printf '%s' "$p"
}

# open_url URL — best-effort launch of the user's default browser on URL via
# `xdg-open` (Linux-only project, matching --help/README scope). Resolved via
# PATH (never a hard-coded absolute path) so tests can put a fake-bin stub
# first on PATH; OPENER lets a caller override the binary name entirely (also
# resolved via `command -v`, so it stays stubbable). Launched in the
# background so it never blocks the boot flow; missing/failing opener is a
# warning, never fatal — the URL was already printed, so the user can always
# open it by hand.
open_url() {
  local url="$1" opener="${OPENER:-xdg-open}" opener_path
  if ! opener_path="$(command -v "$opener" 2>/dev/null)"; then
    warn "--open: '$opener' not found on PATH — open this URL yourself: $url"
    return 0
  fi
  "$opener_path" "$url" >/dev/null 2>&1 &
  info "--open: launching $opener for $url"
}

# derive_project_settings REPO_PATH — sets SLUG, PORT, PORT_OK, PROJECT_ENV,
# PROJECT_NAME, COMPOSE in the caller's scope, mirroring exactly what the boot
# flow computes in steps 5/6, WITHOUT pulling/booting/attaching anything.
# Shared by the boot flow and the --status/--down management commands so they
# all agree on which stack a given repo path maps to. Like boot, this
# (re)writes the per-project env file at .envs/<slug>.env so --env-file always
# matches what's actually running.
derive_project_settings() {
  local repo_path="$1"

  SLUG="$(derive_slug "$repo_path")"

  PORT=4096
  PORT_OK=1
  if port_in_use 4096; then
    PORT_OK=0
    PORT="$(find_free_port 4097 4196)"
  fi

  local user_layer_path
  user_layer_path="$(get_env USER_LAYER_PATH)"
  local compose_files
  compose_files=(-f "$__OCL_DIR/docker/docker-compose.yml")
  if [ -n "$user_layer_path" ]; then
    mkdir -p "$user_layer_path"
    user_layer_path="$(cd -- "$user_layer_path" >/dev/null 2>&1 && pwd)" \
      || die "could not resolve USER_LAYER_PATH"
    compose_files+=(-f "$__OCL_DIR/docker/docker-compose.user-layer.yml")
  fi

  mkdir -p "$ENVS_DIR"
  PROJECT_ENV="${ENVS_DIR}/${SLUG}.env"
  {
    cat "$ENV_FILE"
    echo
    echo "# --- per-project (generated by start.sh; do not edit by hand) ---"
    echo "PROJECT_SLUG=${SLUG}"
    echo "OPENCODE_PORT=${PORT}"
    echo "REPO_PATH=${repo_path}"
    [ -n "$user_layer_path" ] && echo "USER_LAYER_PATH=${user_layer_path}"
  } > "$PROJECT_ENV"

  PROJECT_NAME="opencode-${SLUG}"
  # The compose files live under docker/, but their relative paths (build
  # contexts, the :z bind mounts, env_file) must resolve from the repo root.
  # --project-directory pins that base so moving the files stays transparent.
  COMPOSE=(docker compose
    --project-directory "$__OCL_DIR"
    --env-file "$PROJECT_ENV"
    -p "$PROJECT_NAME"
    "${compose_files[@]}")
}
